name: Build Gradle project

on:
  push:
    tags:
      - "*"

env:
  cloudUsername: "VeguiDev"
  cloudPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: cd Forge && chmod +x ./gradlew && ./gradlew build